### ISSUE TITLE
Crash when opening preferences

### ISSUE THREAD

**Issue by bornout** [Atelier-Shiori/Shukofukurou#29]
Mac OS 10.15.4
Shukofukurou Version 3.4

When i try to open the preferences the application crashes direct.
I can send you a crashlog if you need.

**Comment by moyitpro** [comment]
It appears to be an issue with the airing notifications service when the source list is not using AniList, but other service due to an invalid id for a title that couldn't be found on AniList.

I will fix this bug as soon as possible. To open the app again, you need to disable Air Notifications by running this command in the Terminal

App Store version+
 defaults write ~/Library/Containers/moe.malupdaterosx.shukofukurou/Data/Library/Preferences/moe.malupdaterosx.shukofukurou.plist  airnotificationsenabled -bool NO

Non-App Store version
 defaults write ~/Library/Preferences/moe.malupdaterosx.shukofukurou.plist  airnotificationsenabled -bool NO

**Comment by moyitpro** [comment]
Fixed with https://github.com/Atelier-Shiori/Shukofukurou/commit/a405fcac4338d0c17333aa1c702b6bf77d3498f3 and I tested with MyAnimeList as the source list for notifications and it doesn't crash. 3.4.1 with the fix will be released in a few days after approved on the App Store.
