### ISSUE TITLE
App continually crashes

### ISSUE THREAD

**Issue by cirrusbottle** [Atelier-Shiori/Shukofukurou#37]
Within the past month, when updating an entry, Shukofukurou suddenly crashed on me. Whenever I try to open it now, it closes before I can do anything. 
I tried deleting the app and reinstalling, but it seems like it retains my login information and the issue persists.

**Comment by moyitpro** [comment]
Which service are you using normally. Is this the Mac or iOS version?

Sent from my iPhone 11 Pro
(Shijou Takane - 四条貴音)

**Comment by cirrusbottle** [comment]
It’s the MacOS version.

**Comment by moyitpro** [comment]
I see the crashes for the 3.4.1. I apparently forgot to release 3.4.3, which probably fixes the issue, but since I forgot to release that version and worked on 3.5, I will be releasing that instead.

See if the 3.5 Beta 2 resolve the issue (The app store app should unlock the paid features). I will be releasing the 3.5 to the App Store soon after I fix some bugs:

https://github.com/Atelier-Shiori/Shukofukurou/releases/tag/3.5-beta2

**Comment by cirrusbottle** [comment]
Thanks! It seems like the 3.5 beta fixes the issues I was having.

**Comment by cirrusbottle** [comment]
After doing a little troubleshooting,  I think the issue was with MyAnimeList. Trying to access my MAL account on Shukofukurou Next caused it to crash immediately again, but I managed to get it to stop by switching to my AniList account quickly and logging out of my MAL account. 

However, when I tried to reauthorize my MAL account, the page opened showed a 404 error.

**Comment by moyitpro** [comment]
I will take a look at it tomorrow. AppCenter crash reports should provide some clues

Sent from my iPhone 11 Pro
(Shijou Takane - 四条貴音)

**Comment by moyitpro** [comment]
Finally pinpointed the error. It's one of the fields being set as null in the manga list entries, but I do not know what field since it doesn't crash with mine, so I created a method that checks all the fields and set them as blank if there is any nil values so it won't crash. 

If you provide your username, I can probably load the list into the MAL API directly to see exactly what fields are causing it to not populate properly.

**Comment by moyitpro** [comment]
[Shukofukurou Next.dmg.zip](https://github.com/Atelier-Shiori/Shukofukurou/files/5831907/Shukofukurou.Next.dmg.zip)
See if this build fixes your issue.

**Comment by cirrusbottle** [comment]
I was able to log into my MAL account again, but the crashes continue. My MAL username is thejesster101, so I hope that helps.

**Comment by moyitpro** [comment]
I found the culprit. Apparently, one of your manga entries, "Pochapocha Suiei-bu" does not have a reading status set. I know this is probably a glitch as it's impossible to set no read/watch status for an entry, but it apparently exists. If you set a read status, it will resolve the crashing issue. I made a fix so that the app won't crash if these entries exist.

**Comment by moyitpro** [comment]
https://github.com/Atelier-Shiori/Shukofukurou/releases/tag/3.5-beta3

**Comment by moyitpro** [comment]
Does this solve your issue? Please respond.

**Comment by cirrusbottle** [comment]
It does indeed fix the issues! Thanks for your help.
