### ISSUE TITLE
"Enable Airing Notifications" button does not work 

### ISSUE THREAD

**Issue by funkymonkey17** [Atelier-Shiori/Shukofukurou#39]
I have the latest version of BigSur at the moment and when I press the Enable Airing Notifications button, it does not allow me to check it.

**Comment by moyitpro** [comment]
This happens since you need to enable notifications for this app. I will make a change to alert the user to enable notifications for the app. Enable notifications for Shukofukurou in the Notification preferences in System Preferences.

![2021-04-03_11-18-10](https://user-images.githubusercontent.com/161183/113482831-6367ea00-946e-11eb-8caf-eb289d92fe96.png)

I will close this.
